applications/security/urls.py
from django.urls import path

from applications.security.views.auth import signin, signout
from applications.security.views.menu import MenuCreateView, MenuDeleteView, MenuListView, MenuUpdateView
from applications.security.views.groups import GroupsListView, GroupsCreateView, GroupsUpdateView, GroupsDeleteView
from applications.security.views.users import UserListView, UserCreateView, UserUpdateView, UserDeleteView
from applications.security.views.group_module_permission import GroupModulePermissionListView, GroupModulePermissionCreateView, GroupModulePermissionUpdateView, GroupModulePermissionDeleteView, get_module_permissions
from applications.security.views.module import ModuleCreateView, ModuleDeleteView, ModuleListView, ModuleUpdateView


app_name='security' # define un espacio de nombre para la aplicacion
urlpatterns = [

  # rutas de modulos
  path('module_list/',ModuleListView.as_view() ,name="module_list"),
  path('module_create/', ModuleCreateView.as_view(),name="module_create"),
  path('module_update/<int:pk>/', ModuleUpdateView.as_view(),name='module_update'),
  path('module_delete/<int:pk>/', ModuleDeleteView.as_view(),name='module_delete'),

# rutas de menus
  path('menu_list/',MenuListView.as_view() ,name="menu_list"),
  path('menu_create/', MenuCreateView.as_view(),name="menu_create"),
  path('menu_update/<int:pk>/', MenuUpdateView.as_view(),name='menu_update'),
  path('menu_delete/<int:pk>/', MenuDeleteView.as_view(),name='menu_delete'),

# Rutas de Groups
  path('group_list/', GroupsListView.as_view(), name='group_list'),
  path('group_create/', GroupsCreateView.as_view(),name="groups_create"),
  path('group_update/<int:pk>/', GroupsUpdateView.as_view(),name='group_update'),
  path('group_delete/<int:pk>/', GroupsDeleteView.as_view(),name='group_delete'),

# Rutas de Usuarios
  path('user_list/', UserListView.as_view(), name='user_list'),
  path('user_create/', UserCreateView.as_view(),name="users_create"),
  path('user_update/<int:pk>/', UserUpdateView.as_view(),name='user_update'),
  path('user_delete/<int:pk>/', UserDeleteView.as_view(),name='user_delete'),


    # rutas para GroupModulePermission
    path('groupmodulepermission_list/', 
         GroupModulePermissionListView.as_view(), 
         name='groupmodulepermission_list'),
    path('groupmodulepermission_create/', 
         GroupModulePermissionCreateView.as_view(), 
         name='groupmodulepermission_create'),
    path('groupmodulepermission_update/<int:pk>/', 
         GroupModulePermissionUpdateView.as_view(), 
         name='groupmodulepermission_update'),
    path('groupmodulepermission_delete/<int:pk>/', 
         GroupModulePermissionDeleteView.as_view(), 
         name='groupmodulepermission_delete'),
    
    # Nueva ruta para obtener permisos por módulo (AJAX)
    # RUTA AJAX PARA OBTENER PERMISOS DEL MÓDULO
    path('get_module_permissions/', get_module_permissions, name="get_module_permissions"),

  # rutas de autenticacion
  path('logout/', signout, name='signout'),
  path('signin/', signin, name='signin'),
  #path('signup/', signup, name='signup'),
]

proy_clinico/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from applications.security.views.home import ModuloTemplateView

def redirect_pago_exitoso(request):
    return redirect('/doctor/pago-exitoso/')

def redirect_pago_cancelado(request):
    return redirect('/doctor/pago-cancelado/')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ModuloTemplateView.as_view(), name='home'),
    path('security/', include('applications.security.urls', namespace='security')),
    path('core/', include('applications.core.urls', namespace='core')),
    path('doctor/', include('applications.doctor.urls', namespace='doctor')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('pago-exitoso/', redirect_pago_exitoso),
    path('pago-cancelado/', redirect_pago_cancelado),
    path('chatbot/', include('applications.chatbot.urls', namespace='chatbot')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/security/views.py
# from django.shortcuts import render

# def home(request): 
#     return render(request, 'home.html')

applications/security/views/group_module_permission.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from django.db.models import Q
from django.contrib.auth.models import Group
from applications.security.models import GroupModulePermission, Module
from applications.security.forms.group_module_permission import GroupModulePermissionForm
from applications.security.components.mixin_crud import (
    ListViewMixin, CreateViewMixin, UpdateViewMixin, DeleteViewMixin, PermissionMixin
)


class GroupModulePermissionListView(PermissionMixin, ListViewMixin, ListView):
    template_name = 'security/group_module_permission/list.html'
    model = GroupModulePermission
    context_object_name = 'group_permissions'
    permission_required = 'view_groupmodulepermission'
    
    def get_queryset(self):
        q = self.request.GET.get('q')
        if q:
            self.query.add(Q(group__name__icontains=q), Q.OR)
            self.query.add(Q(module__name__icontains=q), Q.OR)
            self.query.add(Q(module__menu__name__icontains=q), Q.OR)
        return self.model.objects.select_related('group', 'module', 'module__menu').filter(self.query).order_by('group__name', 'module__name')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('security:groupmodulepermission_create')
        return context


class GroupModulePermissionCreateView(PermissionMixin, CreateViewMixin, CreateView):
    model = GroupModulePermission
    form_class = GroupModulePermissionForm
    template_name = 'security/group_module_permission/form.html'
    success_url = reverse_lazy('security:groupmodulepermission_list')
    permission_required = 'add_groupmodulepermission'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Crear Permiso de Grupo'
        context['back_url'] = self.success_url
        return context
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request, 
            f"Éxito al crear el permiso para el grupo: {self.object.group.name} - {self.object.module.name}."
        )
        return response


class GroupModulePermissionUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
    model = GroupModulePermission
    form_class = GroupModulePermissionForm
    template_name = 'security/group_module_permission/form.html'
    success_url = reverse_lazy('security:groupmodulepermission_list')
    permission_required = 'change_groupmodulepermission'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Actualizar Permiso de Grupo'
        context['back_url'] = self.success_url
        return context
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request, 
            f"Éxito al actualizar el permiso para el grupo: {self.object.group.name} - {self.object.module.name}."
        )
        return response


class GroupModulePermissionDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
    model = GroupModulePermission
    template_name = 'core/delete.html'
    success_url = reverse_lazy('security:groupmodulepermission_list')
    permission_required = 'delete_groupmodulepermission'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Eliminar Permiso de Grupo'
        context['description'] = f"¿Desea eliminar el permiso del grupo: {self.object.group.name} para el módulo: {self.object.module.name}?"
        context['back_url'] = self.success_url
        return context
    
    def form_valid(self, form):
        group_name = self.object.group.name
        module_name = self.object.module.name
        response = super().form_valid(form)
        messages.success(
            self.request, 
            f"Éxito al eliminar el permiso del grupo: {group_name} para el módulo: {module_name}."
        )
        return response


# Vista AJAX para obtener permisos del módulo
def get_module_permissions(request):
    """
    Vista AJAX para obtener los permisos disponibles para un módulo específico
    """
    module_id = request.GET.get('module_id')
    if not module_id:
        return JsonResponse({'permissions': []})
    
    try:
        module = Module.objects.get(id=module_id)
        permissions = module.permissions.all().values('id', 'name', 'codename')
        return JsonResponse({'permissions': list(permissions)})
    except Module.DoesNotExist:
        return JsonResponse({'permissions': []})

applications/security/views/groups.py
from django.contrib import messages
from django.urls import reverse_lazy
from applications.security.components.mixin_crud import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin
from applications.security.forms.menu import MenuForm
from applications.security.forms.module import ModuleForm
from applications.security.forms.groups import GroupForm
from applications.security.models import Menu, Module, Group
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q


class GroupsListView(PermissionMixin, ListViewMixin, ListView):
    model = Group
    template_name = 'security/groups/list.html'
    context_object_name = 'groups'
    permission_required = 'view_group'

    def get_queryset(self):
        q = self.request.GET.get('q')
        if q is not None:
            self.query.add(Q(name__icontains=q), Q.OR)
            
        return self.model.objects.filter(self.query).order_by('id')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('security:groups_create')
        return context
    
class GroupsCreateView(PermissionMixin, CreateViewMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'security/groups/form.html'
    permission_required = 'add_group'
    success_url = reverse_lazy('security:group_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Crear'
        context['back_url'] = self.success_url
        return context
    def form_valid(self, form):
        response = super().form_valid(form)
        object = self.object.name
        messages.success(self.request, f'Grupo {object} creado correctamente')
        return response
    
class GroupsUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = 'security/groups/form.html'
    permission_required = 'change_group'
    success_url = reverse_lazy('security:group_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['grabar'] = 'Actualizar'
        context['back_url'] = self.success_url
        return context
    
    def form_valid(self, form):
        response = super().form_valid(form)
        object = self.object.name
        messages.success(self.request, f'Grupo {object} actualizado correctamente')
        return response
    
class GroupsDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
    model = Group
    template_name = 'security/groups/delete.html'
    permission_required = 'delete_group'
    success_url = reverse_lazy('security:group_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['back_url'] = self.success_url
        context['decription'] = '¿ Estas seguro de eliminar este grupo ? '

        return context
    
    def form_valid(self, form):
        response = super().form_valid(form)
        object = self.object.name
        messages.success(self.request, f'Grupo {object} eliminado correctamente')
        return response
        

applications/security/views/home.py
from django.views.generic import TemplateView
from applications.security.components.menu_module import MenuModule
from applications.security.components.mixin_crud import PermissionMixin

class ModuloTemplateView(PermissionMixin,TemplateView):
    template_name = 'home.html'
   
    def get_context_data(self, **kwargs):
        #context = super().get_context_data(**kwargs)
        context={}
        context["title"]= "IC - Modulos"
        context["title1"]= "Modulos Disponibles"
        MenuModule(self.request).fill(context)
        
        print("estoy saliendo en el modulo template view")
       
        return context

applications/security/views/menu.py
from django.contrib import messages
from django.urls import reverse_lazy
from applications.security.components.mixin_crud import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin
from applications.security.forms.menu import MenuForm
from applications.security.forms.module import ModuleForm
from applications.security.models import Menu, Module
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q


class MenuListView(PermissionMixin, ListViewMixin, ListView):
    template_name = 'security/menus/list.html'
    model = Menu
    context_object_name = 'menus'
    permission_required = 'view_menu'

    def get_queryset(self):
        q1 = self.request.GET.get('q')
        if q1 is not None:
            self.query.add(Q(name__icontains=q1), Q.OR)
           
        return self.model.objects.filter(self.query).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('security:menu_create')
        print(context['permissions'])
        return context


class MenuCreateView(PermissionMixin, CreateViewMixin, CreateView):
    model = Menu
    template_name = 'security/menus/form.html'
    form_class = MenuForm
    success_url = reverse_lazy('security:menu_list')
    permission_required = 'add_menu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Grabar Menu'
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        menu = self.object
        messages.success(self.request, f"Éxito al crear el menu {menu.name}.")
        return response


class MenuUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
    model = Menu
    template_name = 'security/menus/form.html'
    form_class = MenuForm
    success_url = reverse_lazy('security:menu_list')
    permission_required = 'change_menu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Actualizar Menu'
        context['back_url'] = self.success_url
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        menu = self.object
        messages.success(self.request, f"Éxito al actualizar el menu {menu.name}.")
        return response


class MenuDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
    model = Menu
    template_name = 'core/delete.html'
    success_url = reverse_lazy('security:menu_list')
    permission_required = 'delete_menu'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['grabar'] = 'Eliminar Menu'
        context['description'] = f"¿Desea eliminar el menu: {self.object.name}?"
        context['back_url'] = self.success_url
        return context

    
    def form_valid(self, form):
        # Guardar info antes de eliminar
        menu_name = self.object.name
        
        # Llamar al delete del padre
        response = super().form_valid(form)
        
        # Agregar mensaje
        messages.success(self.request, f"Éxito al eliminar lógicamente el menu {menu_name}.")
        
        return response

templates/security/modules/list.html
{% extends 'home.html' %} 
<title>{% block title %}{{title}}{% endblock %}</title>
{% block content %}
    {% load static %}
    {% include 'fragments/messages.html' %}
    <section class="dark:bg-principal mt-2">
        <div class="text-center" data-aos="fade-up" data-aos-delay="200">
            <div class="sm:pt-8 lg:pt-4">
                
                    <h1 class="rounded-2xl  bg-indigo-500 px-2 py-1 text-white uppercase text-4xl">
                        {{ title1 }}
                    </h1>
               
            
               
            </div>
            <div class="lg:p-2 rounded-3xl" data-aos="fade-up" data-aos-delay="200">
                <!-- Barra de búsqueda -->
                <div class="p-4 flex justify-center">
                    <label for="table-search" class="sr-only">Search</label>
                    <div class="relative mt-1">
                        <div
                            class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                    stroke-width="2"
                                    d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                            </svg>
                        </div>
                        <form method="GET" >
                            <input type="text" name="q" id="table-search"
                                class="text-center pl-10 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 pr-12 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                                placeholder="Búsqueda sin límites" value="{{ request.GET.q }}">
                        </form>
                    </div>
                </div>
                <!-- Tabla de módulos -->
                <div class="overflow-x-auto">
                    <table class="w-full text-center text-lg">
                        <thead class="uppercase font-Tiny5 bg-gray-50 dark:bg-secundario dark:text-blue-300">
                            <tr>
                                <th scope="col" class="px-6 py-3">ID</th>
                                <th scope="col" class="px-6 py-3">Icono</th>
                                <th scope="col" class="px-6 py-3">Nombre</th>
                                <th scope="col" class="px-6 py-3">URL</th>
                                <th scope="col" class="px-6 py-3">Menú</th>
                                <th scope="col" class="px-6 py-3">Descripción</th>
                                <th scope="col" class="px-6 py-3">Orden</th>
                                <th scope="col" class="px-6 py-3">Estado</th>
                                <th scope="col" class="px-6 py-3">Permisos</th>
                                <th scope="col" class="px-6 py-3">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in modules %}
                            <tr class="dark:text-gray-400 bg-white border-b dark:bg-[#0b1121] dark:border-secundario hover:bg-gray-50 dark:hover:bg-[#121c33]">
                                <td class="px-6 py-4">{{ item.id }}</td>
                                <td class="px-6 py-4">
                                    <i class="{{ item.icon }} text-2xl text-blue-600 dark:text-blue-400"></i>
                                </td>
                                <td class="px-6 py-4 font-semibold">{{ item.name }}</td>
                                <td class="px-6 py-4">
                                    <code class="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded text-sm">
                                        {{ item.url }}
                                    </code>
                                </td>
                                <td class="px-6 py-4">
                                    <span class="bg-indigo-100 dark:bg-indigo-900 text-indigo-800 dark:text-indigo-200 px-2 py-1 rounded-full text-sm">
                                        {{ item.menu.name }}
                                    </span>
                                </td>
                                <td class="px-6 py-4">
                                    {% if item.description %}
                                        {{ item.description|truncatechars:50 }}
                                    {% else %}
                                        <span class="text-gray-400 italic">Sin descripción</span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4">
                                    <span class="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded-full text-sm">
                                        {{ item.order }}
                                    </span>
                                </td>
                                <td class="px-6 py-4">
                                    {% if item.is_active %}
                                        <span class="bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200 px-2 py-1 rounded-full text-sm">
                                            <i class="fa-solid fa-check mr-1"></i>Activo
                                        </span>
                                    {% else %}
                                        <span class="bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200 px-2 py-1 rounded-full text-sm">
                                            <i class="fa-solid fa-times mr-1"></i>Inactivo
                                        </span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4">
                                    <span class="bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 py-1 rounded-full text-sm">
                                        {{ item.permissions.count }} permisos
                                    </span>
                                </td>
                                <td class="px-6 py-4">
                                  {% if permissions.change_module %}
                                    <a href="{% url 'security:module_update' item.id %}"
                                        class="text-blue-600 dark:text-blue-500 hover:text-blue-800 mx-1">
                                        <i class="fa-solid fa-edit text-lg"></i>
                                    </a>
                                  {% endif%}  
                                  {% if permissions.delete_module %}
                                    <a href="#"
                                        class="text-red-600 dark:text-red-500 hover:text-red-800 mx-1"
                                        onclick="openDeleteModal('{{ item.id }}', '{{ item.name }}')">
                                        <i class="fa-solid fa-trash text-lg"></i>
                                    </a>
                                  {% endif %} 
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- Paginación -->
                <div class="flex justify-center mt-4">
                    <nav aria-label="Page navigation example">
                        <ul class="inline-flex -space-x-px">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                    class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Anterior</a>
                            </li>
                            {% endif %}
                            {% for num in page_obj.paginator.page_range %}
                            <li>
                                <a href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                    class="flex items-center justify-center px-3 h-8 leading-tight {% if num == page_obj.number %}text-blue-600 bg-blue-50 border border-gray-300 hover:bg-blue-100 hover:text-blue-700 dark:bg-secundario dark:border-principal dark:text-blue-300{% else %}text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white{% endif %}">
                                    {{ num }}
                                </a>
                            </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li>
                                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                                    class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Siguiente</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>

                <!-- Enlaces adicionales -->
                <div class="flex flex-col md:flex-row justify-center form-group text-center p-4">
                    {% if permissions.add_module %}
                    <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full mr-0 md:mr-2 mb-2 md:mb-0 flex items-center justify-center transition-colors duration-300"
                        href="{% url 'security:module_create' %}">
                        <i class="fa-solid fa-plus mr-2"></i> Nuevo Módulo
                    </a>
                    {% endif %}
                    <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full flex items-center justify-center transition-colors duration-300"
                        href="{% url 'home' %}">
                        <i class="fa-solid fa-house"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>

    {% include 'fragments/delete.html' %}
   <script>
function openDeleteModal(id, name) {
    const deleteForm = document.getElementById('deleteForm');
    deleteForm.action = `{% url 'security:module_delete' 0 %}`.replace('0', id);
    document.getElementById('Description').textContent = `ID: ${id} - ${name}`;
    document.getElementById('deleteModal').classList.remove('hidden');
}

function closeModal() {
    document.getElementById('deleteModal').classList.add('hidden');
}

// ✅ AGREGAR: Asegurar redirección correcta
document.addEventListener('DOMContentLoaded', function() {
    const deleteForm = document.getElementById('deleteForm');
    
    if (deleteForm) {
        deleteForm.addEventListener('submit', function(e) {
            // Opcional: Mostrar loading
            const submitBtn = deleteForm.querySelector('button[type="submit"]');
            if (submitBtn) {
                submitBtn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Eliminando...';
                submitBtn.disabled = true;
            }
            
            // Permitir envío normal del formulario
            // Django manejará la redirección automáticamente
        });
    }
});
</script>
{% endblock %}